# Generated by Django 4.2.6 on 2023-11-18 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_remove_user_id_user_unique_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('unique_user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(default='CREDIT CARD', max_length=255)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_period', models.IntegerField(null=True)),
                ('disbursement_date', models.DateField()),
            ],
        ),
    ]
