# Generated by Django 4.2.6 on 2023-11-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_loanapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.CharField(default='CREDIT CARD', max_length=100),
        ),
    ]
