# Generated by Django 4.2.6 on 2023-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_alter_loanapplication_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=3),
        ),
    ]
