# Generated by Django 4.2.6 on 2023-11-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_alter_loanapplication_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_repayments', models.IntegerField()),
                ('total_amount_to_pay', models.IntegerField()),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.loanapplication')),
            ],
        ),
    ]
