# Generated by Django 4.2.6 on 2023-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='due_dates',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
