# Generated by Django 4.2.6 on 2023-11-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_loanapplication_due_dates_loanapplication_emi_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment',
            name='number_of_repayments',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='total_amount_to_pay',
        ),
        migrations.AddField(
            model_name='repayment',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
