# Generated by Django 4.2.6 on 2023-11-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0009_remove_repayment_number_of_repayments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
