# Generated by Django 4.2.6 on 2023-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_repayment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
