# Generated by Django 4.2.6 on 2023-11-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_alter_repayment_emi_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
